"""create-table-conditions

Revision ID: c14c4b6f36b3
Revises: 0894f3022876
Create Date: 2024-01-11 16:02:26.575786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c14c4b6f36b3"
down_revision: Union[str, None] = "0894f3022876"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conditions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "MAX_CALLS_PER_ENTRYPOINT",
                "MAX_CALLS_PER_SPONSEE",
                name="conditiontype",
            ),
            nullable=True,
        ),
        sa.Column(
            "sponsee_address",
            sa.String(),
            sa.CheckConstraint(
                "(type = 'MAX_CALLS_PER_SPONSEE') = (sponsee_address IS NOT NULL)",
                name="sponsee_address_not_null_constraint",
            ),
            nullable=True,
        ),
        sa.Column(
            "contract_id",
            sa.UUID(),
            sa.CheckConstraint(
                "(type = 'MAX_CALLS_PER_ENTRYPOINT') = (contract_id IS NOT NULL)",
                name="contract_id_not_null_constraint",
            ),
            nullable=True,
        ),
        sa.Column(
            "entrypoint_id",
            sa.UUID(),
            sa.CheckConstraint(
                "(type = 'MAX_CALLS_PER_ENTRYPOINT') = (entrypoint_id IS NOT NULL)",
                name="entrypoint_id_not_null_constraint",
            ),
            nullable=True,
        ),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("max", sa.Integer(), nullable=False),
        sa.Column("current", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entrypoint_id"],
            ["entrypoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["credits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conditions")
    op.execute("DROP type conditiontype")
    # ### end Alembic commands ###
