name: Docker ghostnet

on:
  repository_dispatch:
      types: [from-release-coord-repo]

jobs:
  ui:
    strategy:
      matrix:
        network: [ghostnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          submodules: true

      - if: github.event_name == 'repository_dispatch'
        run: |
            VERSION=${{ toJson(github.event.client_payload.version) }}
            echo "VERSION=-$VERSION" >> $GITHUB_ENV
            echo "Pipeline has been triggered through HTTP. Setting version to $VERSION."
        env:
          VERSION: ${{ toJson(github.event.client_payload.version) }}

      - name: Set outputs
        id: vars
        run: |
          echo "date=$(date +%Y-%m-%dT%H-%M-%S)" >> "${GITHUB_OUTPUT}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Set up Docker Buildx
        uses: docker/Setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push version
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.${{ matrix.network }}
          context: ./
          push: true
          tags: |
            ghcr.io/marigold-dev/gas-station-api-${{ matrix.network }}:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}-release${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

